# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.15

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/szp/Documents/Utility-master

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/szp/Documents/Utility-master

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/szp/Documents/Utility-master/CMakeFiles /home/szp/Documents/Utility-master/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/szp/Documents/Utility-master/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named TestContain

# Build rule for target.
TestContain: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 TestContain
.PHONY : TestContain

# fast build rule for target.
TestContain/fast:
	$(MAKE) -f CMakeFiles/TestContain.dir/build.make CMakeFiles/TestContain.dir/build
.PHONY : TestContain/fast

#=============================================================================
# Target rules for targets named sserver

# Build rule for target.
sserver: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sserver
.PHONY : sserver

# fast build rule for target.
sserver/fast:
	$(MAKE) -f CMakeFiles/sserver.dir/build.make CMakeFiles/sserver.dir/build
.PHONY : sserver/fast

HttpUtility.o: HttpUtility.cpp.o

.PHONY : HttpUtility.o

# target to build an object file
HttpUtility.cpp.o:
	$(MAKE) -f CMakeFiles/TestContain.dir/build.make CMakeFiles/TestContain.dir/HttpUtility.cpp.o
	$(MAKE) -f CMakeFiles/sserver.dir/build.make CMakeFiles/sserver.dir/HttpUtility.cpp.o
.PHONY : HttpUtility.cpp.o

HttpUtility.i: HttpUtility.cpp.i

.PHONY : HttpUtility.i

# target to preprocess a source file
HttpUtility.cpp.i:
	$(MAKE) -f CMakeFiles/TestContain.dir/build.make CMakeFiles/TestContain.dir/HttpUtility.cpp.i
	$(MAKE) -f CMakeFiles/sserver.dir/build.make CMakeFiles/sserver.dir/HttpUtility.cpp.i
.PHONY : HttpUtility.cpp.i

HttpUtility.s: HttpUtility.cpp.s

.PHONY : HttpUtility.s

# target to generate assembly for a file
HttpUtility.cpp.s:
	$(MAKE) -f CMakeFiles/TestContain.dir/build.make CMakeFiles/TestContain.dir/HttpUtility.cpp.s
	$(MAKE) -f CMakeFiles/sserver.dir/build.make CMakeFiles/sserver.dir/HttpUtility.cpp.s
.PHONY : HttpUtility.cpp.s

TestContain.o: TestContain.cpp.o

.PHONY : TestContain.o

# target to build an object file
TestContain.cpp.o:
	$(MAKE) -f CMakeFiles/TestContain.dir/build.make CMakeFiles/TestContain.dir/TestContain.cpp.o
.PHONY : TestContain.cpp.o

TestContain.i: TestContain.cpp.i

.PHONY : TestContain.i

# target to preprocess a source file
TestContain.cpp.i:
	$(MAKE) -f CMakeFiles/TestContain.dir/build.make CMakeFiles/TestContain.dir/TestContain.cpp.i
.PHONY : TestContain.cpp.i

TestContain.s: TestContain.cpp.s

.PHONY : TestContain.s

# target to generate assembly for a file
TestContain.cpp.s:
	$(MAKE) -f CMakeFiles/TestContain.dir/build.make CMakeFiles/TestContain.dir/TestContain.cpp.s
.PHONY : TestContain.cpp.s

sserver.o: sserver.cpp.o

.PHONY : sserver.o

# target to build an object file
sserver.cpp.o:
	$(MAKE) -f CMakeFiles/sserver.dir/build.make CMakeFiles/sserver.dir/sserver.cpp.o
.PHONY : sserver.cpp.o

sserver.i: sserver.cpp.i

.PHONY : sserver.i

# target to preprocess a source file
sserver.cpp.i:
	$(MAKE) -f CMakeFiles/sserver.dir/build.make CMakeFiles/sserver.dir/sserver.cpp.i
.PHONY : sserver.cpp.i

sserver.s: sserver.cpp.s

.PHONY : sserver.s

# target to generate assembly for a file
sserver.cpp.s:
	$(MAKE) -f CMakeFiles/sserver.dir/build.make CMakeFiles/sserver.dir/sserver.cpp.s
.PHONY : sserver.cpp.s

type/pObject.o: type/pObject.cpp.o

.PHONY : type/pObject.o

# target to build an object file
type/pObject.cpp.o:
	$(MAKE) -f CMakeFiles/TestContain.dir/build.make CMakeFiles/TestContain.dir/type/pObject.cpp.o
.PHONY : type/pObject.cpp.o

type/pObject.i: type/pObject.cpp.i

.PHONY : type/pObject.i

# target to preprocess a source file
type/pObject.cpp.i:
	$(MAKE) -f CMakeFiles/TestContain.dir/build.make CMakeFiles/TestContain.dir/type/pObject.cpp.i
.PHONY : type/pObject.cpp.i

type/pObject.s: type/pObject.cpp.s

.PHONY : type/pObject.s

# target to generate assembly for a file
type/pObject.cpp.s:
	$(MAKE) -f CMakeFiles/TestContain.dir/build.make CMakeFiles/TestContain.dir/type/pObject.cpp.s
.PHONY : type/pObject.cpp.s

type/pString.o: type/pString.cpp.o

.PHONY : type/pString.o

# target to build an object file
type/pString.cpp.o:
	$(MAKE) -f CMakeFiles/TestContain.dir/build.make CMakeFiles/TestContain.dir/type/pString.cpp.o
.PHONY : type/pString.cpp.o

type/pString.i: type/pString.cpp.i

.PHONY : type/pString.i

# target to preprocess a source file
type/pString.cpp.i:
	$(MAKE) -f CMakeFiles/TestContain.dir/build.make CMakeFiles/TestContain.dir/type/pString.cpp.i
.PHONY : type/pString.cpp.i

type/pString.s: type/pString.cpp.s

.PHONY : type/pString.s

# target to generate assembly for a file
type/pString.cpp.s:
	$(MAKE) -f CMakeFiles/TestContain.dir/build.make CMakeFiles/TestContain.dir/type/pString.cpp.s
.PHONY : type/pString.cpp.s

type/stack.o: type/stack.cpp.o

.PHONY : type/stack.o

# target to build an object file
type/stack.cpp.o:
	$(MAKE) -f CMakeFiles/TestContain.dir/build.make CMakeFiles/TestContain.dir/type/stack.cpp.o
.PHONY : type/stack.cpp.o

type/stack.i: type/stack.cpp.i

.PHONY : type/stack.i

# target to preprocess a source file
type/stack.cpp.i:
	$(MAKE) -f CMakeFiles/TestContain.dir/build.make CMakeFiles/TestContain.dir/type/stack.cpp.i
.PHONY : type/stack.cpp.i

type/stack.s: type/stack.cpp.s

.PHONY : type/stack.s

# target to generate assembly for a file
type/stack.cpp.s:
	$(MAKE) -f CMakeFiles/TestContain.dir/build.make CMakeFiles/TestContain.dir/type/stack.cpp.s
.PHONY : type/stack.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... TestContain"
	@echo "... sserver"
	@echo "... HttpUtility.o"
	@echo "... HttpUtility.i"
	@echo "... HttpUtility.s"
	@echo "... TestContain.o"
	@echo "... TestContain.i"
	@echo "... TestContain.s"
	@echo "... sserver.o"
	@echo "... sserver.i"
	@echo "... sserver.s"
	@echo "... type/pObject.o"
	@echo "... type/pObject.i"
	@echo "... type/pObject.s"
	@echo "... type/pString.o"
	@echo "... type/pString.i"
	@echo "... type/pString.s"
	@echo "... type/stack.o"
	@echo "... type/stack.i"
	@echo "... type/stack.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

